Update aws-deploy.yml

diff --git a/.github/workflows/aws-deploy.yml b/.github/workflows/aws-deploy.yml
--- a/.github/workflows/aws-deploy.yml
+++ b/.github/workflows/aws-deploy.yml
@@ -50,6 +50,7 @@ jobs:
       
           echo "Current latest image tag: $latest_image"
           echo "$latest_image" > previous_latest_image.txt
+          cat previous_latest_image.txt
 
       - name: Build Docker image
         run: docker build -t mindme-prod .
@@ -108,18 +109,31 @@ jobs:
           aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REPOSITORY }}
           
       - name: Save previous latest image tag
+        run: |
+          if [ -f "previous_latest_image.txt" ]; then
+            echo "File exists. Uploading..."
+          else
+            echo "Error: previous_latest_image.txt not found!"
+            exit 1
+          fi
+      
+      - name: Upload previous latest image tag
         uses: actions/upload-artifact@v4
         with:
           name: previous-latest-image
           path: previous_latest_image.txt
 
+
       - name: Download previous latest image tag
         uses: actions/download-artifact@v4
         with:
           name: previous-latest-image
+          path: .
       
       - name: Read the previous latest image tag
         run: |
+          ls -l previous_latest_image.txt  # Check if file is downloaded
+          cat previous_latest_image.txt  # Display contents
           PREVIOUS_LATEST_IMAGE=$(cat previous_latest_image.txt)
           echo "PREVIOUS_LATEST_IMAGE=$PREVIOUS_LATEST_IMAGE" >> $GITHUB_ENV
           echo "Restoring previous latest image: $PREVIOUS_LATEST_IMAGE"
